<div align="right" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img
 src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/alx-courses/aice/assets/Content_page_banner_blue_dots.png"
 alt="ALX Content Header"
 class="full-width-image"
/>
</div>

# SELECT and SELECT WHERE

In this walk-through we demonstrate how to get data out of a table using the SELECT statement.
We also show how to filter data using the where clause.

> ⚠️ This notebook will not run on Google Colab because it cannot connect to a local database. Please make sure that this notebook is running on the same local machine as your MySQL Workbench installation and MySQL `united_nations` database.

## Learning objectives

In this train, we will learn:
- How to use SELECT and SELECT DISTINCT to select columns.
- How to use WHERE to filter data based on a condition.
- Save results sets as new tables.

## Connecting to our MySQL database

Using our `Access_to_Basic_Services` table in our `united_nations` database we created in MySQL Workbench, we want to answer some questions about our dataset. We can apply the same queries we used in MySQL Workbench in this notebook if we connect to our MySQL server by running the cells below.

In [1]:
# Load and activate the SQL extension to allow us to execute SQL in a Jupyter notebook. 
# If you get an error here, make sure that mysql and pymysql are installed correctly. 

%load_ext sql

In [8]:
# Establish a connection to the local database using the '%sql' magic command.
# Replace 'password' with our connection password and `db_name` with our database name. 
# If you get an error here, please make sure the database name or password is correct.

%sql mysql+pymysql://root:12122001UPi@localhost:3306/united_nations

Connecting and switching to connection 'mysql+pymysql://root:***@localhost:3306/united_nations'


To make a query, we add the `%%sql` command to the start of a cell, create one open line, then the query like below, and run the cell.

In [24]:
%config SqlMagic.displaylimit = None

displaylimit: Value None will be treated as 0 (no limit)

In [9]:
%%sql

SELECT 
    *
FROM
    Access_to_Basic_Services
LIMIT 5;

Running query in 'mysql+pymysql://root:***@localhost:3306/united_nations'

5 rows affected.

+---------------------------+--------------+--------------+-------------+-------------------------------------+---------------------------------+----------------------------+---------------------+------------+------------------+
|           Region          |  Sub_region  | Country_name | Time_period | Pct_managed_drinking_water_services | Pct_managed_sanitation_services | Est_population_in_millions | Est_gdp_in_billions | Land_area  | Pct_unemployment |
+---------------------------+--------------+--------------+-------------+-------------------------------------+---------------------------------+----------------------------+---------------------+------------+------------------+
| Central and Southern Asia | Central Asia |  Kazakhstan  |     2015    |                94.67                |              98.00              |         17.542806          |        184.39       | 2699700.00 |       4.93       |
| Central and Southern Asia | Central Asia |  Kazakhstan  |     2016    |                94.67                |              98.00              |         17.794055          |        137.28       | 2699700.00 |       4.96       |
| Central and Southern Asia | Central Asia |  Kazakhstan  |     2017    |                95.00                |              98.00              |         18.037776          |        166.81       | 2699700.00 |       4.90       |
| Central and Southern Asia | Central Asia |  Kazakhstan  |     2018    |                95.00                |              98.00              |         18.276452          |        179.34       | 2699700.00 |       4.85       |
| Central and Southern Asia | Central Asia |  Kazakhstan  |     2019    |                95.00                |              98.00              |         18.513673          |        181.67       | 2699700.00 |       4.80       |
+---------------------------+--------------+--------------+-------------+-------------------------------------+---------------------------------+----------------------------+---------------------+------------+------------------+

## Exercise

Suppose we want to find out which country had the lowest percentage of people with access to managed drinking water services in 2020.

### 1. Exploring the database

Use the `SELECT` statement to display all the columns from the `Access_to_Basic_Services` table. This will help us get a feel for the data we're working with.

In [25]:
%%sql

SELECT 
    *
FROM
    Access_to_Basic_Services
LIMIT 100;

Running query in 'mysql+pymysql://root:***@localhost:3306/united_nations'

100 rows affected.

+--------------------------------+---------------+---------------------------------------+-------------+-------------------------------------+---------------------------------+----------------------------+---------------------+------------+------------------+
|             Region             |   Sub_region  |              Country_name             | Time_period | Pct_managed_drinking_water_services | Pct_managed_sanitation_services | Est_population_in_millions | Est_gdp_in_billions | Land_area  | Pct_unemployment |
+--------------------------------+---------------+---------------------------------------+-------------+-------------------------------------+---------------------------------+----------------------------+---------------------+------------+------------------+
|   Central and Southern Asia    |  Central Asia |               Kazakhstan              |     2015    |                94.67                |              98.00              |         17.542806          |        184.39       | 2699700.00 |       4.93       |
|   Central and Southern Asia    |  Central Asia |               Kazakhstan              |     2016    |                94.67                |              98.00              |         17.794055          |        137.28       | 2699700.00 |       4.96       |
|   Central and Southern Asia    |  Central Asia |               Kazakhstan              |     2017    |                95.00                |              98.00              |         18.037776          |        166.81       | 2699700.00 |       4.90       |
|   Central and Southern Asia    |  Central Asia |               Kazakhstan              |     2018    |                95.00                |              98.00              |         18.276452          |        179.34       | 2699700.00 |       4.85       |
|   Central and Southern Asia    |  Central Asia |               Kazakhstan              |     2019    |                95.00                |              98.00              |         18.513673          |        181.67       | 2699700.00 |       4.80       |
|   Central and Southern Asia    |  Central Asia |               Kazakhstan              |     2020    |                95.00                |              98.00              |         18.755666          |        171.08       | 2699700.00 |       4.89       |
|   Central and Southern Asia    |  Central Asia |               Kyrgyzstan              |     2015    |                89.67                |              96.67              |            None            |         None        |    None    |       None       |
|   Central and Southern Asia    |  Central Asia |               Kyrgyzstan              |     2016    |                90.33                |              96.67              |            None            |         None        |    None    |       None       |
|   Central and Southern Asia    |  Central Asia |               Kyrgyzstan              |     2017    |                91.00                |              97.33              |            None            |         None        |    None    |       None       |
|   Central and Southern Asia    |  Central Asia |               Kyrgyzstan              |     2018    |                91.33                |              97.33              |            None            |         None        |    None    |       None       |
|   Central and Southern Asia    |  Central Asia |               Kyrgyzstan              |     2019    |                91.67                |              97.33              |            None            |         None        |    None    |       None       |
|   Central and Southern Asia    |  Central Asia |               Kyrgyzstan              |     2020    |                92.67                |              97.67              |            None            |         None        |    None    |       None       |
|   Central and Southern Asia    |  Central Asia |               Tajikistan              |     2015    |                80.33                |              95.00              |          8.524063          |         8.27        | 138790.00  |       None       |
|   Central and Southern Asia    |  Central Asia |               Tajikistan              |     2016    |                81.33                |              95.33              |          8.725318          |         6.99        | 138790.00  |       6.90       |
|   Central and Southern Asia    |  Central Asia |               Tajikistan              |     2017    |                82.33                |              95.67              |          8.925525          |         7.54        | 138790.00  |       None       |
|   Central and Southern Asia    |  Central Asia |               Tajikistan              |     2018    |                83.33                |              95.67              |          9.128132          |         7.77        | 138790.00  |       None       |
|   Central and Southern Asia    |  Central Asia |               Tajikistan              |     2019    |                85.00                |              96.33              |          9.337003          |         8.30        | 138790.00  |       None       |
|   Central and Southern Asia    |  Central Asia |               Tajikistan              |     2020    |                85.00                |              96.33              |          9.543207          |         8.13        | 138790.00  |       None       |
|   Central and Southern Asia    |  Central Asia |              Turkmenistan             |     2015    |                97.67                |              97.33              |          5.766431          |        35.80        | 469930.00  |       None       |
|   Central and Southern Asia    |  Central Asia |              Turkmenistan             |     2016    |                98.00                |              98.00              |          5.868561          |        36.17        | 469930.00  |       None       |
|   Central and Southern Asia    |  Central Asia |              Turkmenistan             |     2017    |                98.67                |              98.00              |          5.968383          |        37.93        | 469930.00  |       None       |
|   Central and Southern Asia    |  Central Asia |              Turkmenistan             |     2018    |                99.33                |              98.67              |          6.065066          |        40.77        | 469930.00  |       None       |
|   Central and Southern Asia    |  Central Asia |              Turkmenistan             |     2019    |                100.00               |              99.33              |          6.158420          |        45.23        | 469930.00  |       None       |
|   Central and Southern Asia    |  Central Asia |              Turkmenistan             |     2020    |                100.00               |              99.33              |          6.250438          |         None        | 469930.00  |       None       |
|   Central and Southern Asia    |  Central Asia |               Uzbekistan              |     2015    |                97.67                |              100.00             |         31.298900          |        86.20        | 440600.00  |       5.15       |
|   Central and Southern Asia    |  Central Asia |               Uzbekistan              |     2016    |                97.67                |              100.00             |         31.847900          |        86.14        | 440591.00  |       5.16       |
|   Central and Southern Asia    |  Central Asia |               Uzbekistan              |     2017    |                98.00                |              100.00             |         32.388600          |        62.08        | 440588.00  |       5.83       |
|   Central and Southern Asia    |  Central Asia |               Uzbekistan              |     2018    |                98.00                |              100.00             |         32.956100          |        52.63        | 440587.00  |       9.35       |
|   Central and Southern Asia    |  Central Asia |               Uzbekistan              |     2019    |                98.00                |              100.00             |         33.580350          |        59.91        | 440555.00  |       8.98       |
|   Central and Southern Asia    |  Central Asia |               Uzbekistan              |     2020    |                98.00                |              100.00             |         34.232050          |        59.89        | 440650.00  |       5.29       |
|   Central and Southern Asia    | Southern Asia |              Afghanistan              |     2015    |                67.00                |              45.67              |         33.753499          |        20.00        | 652230.00  |       None       |
|   Central and Southern Asia    | Southern Asia |              Afghanistan              |     2016    |                69.67                |              47.00              |         34.636207          |        18.02        | 652230.00  |       None       |
|   Central and Southern Asia    | Southern Asia |              Afghanistan              |     2017    |                72.33                |              49.33              |         35.643418          |        18.90        | 652230.00  |      11.18       |
|   Central and Southern Asia    | Southern Asia |              Afghanistan              |     2018    |                75.33                |              50.67              |         36.686784          |        18.42        | 652230.00  |       None       |
|   Central and Southern Asia    | Southern Asia |              Afghanistan              |     2019    |                78.00                |              52.33              |         37.769499          |        18.90        | 652230.00  |       None       |
|   Central and Southern Asia    | Southern Asia |              Afghanistan              |     2020    |                80.33                |              54.00              |         38.972230          |        20.14        | 652230.00  |      11.71       |
|   Central and Southern Asia    | Southern Asia |               Bangladesh              |     2015    |                97.33                |              47.33              |         157.830000         |        195.08       | 130170.00  |       None       |
|   Central and Southern Asia    | Southern Asia |               Bangladesh              |     2016    |                97.33                |              48.67              |         159.784568         |        265.24       | 130170.00  |       4.35       |
|   Central and Southern Asia    | Southern Asia |               Bangladesh              |     2017    |                97.33                |              50.00              |         161.793964         |        293.75       | 130170.00  |       4.37       |
|   Central and Southern Asia    | Southern Asia |               Bangladesh              |     2018    |                97.33                |              51.33              |         163.683958         |        321.38       | 130170.00  |       None       |
|   Central and Southern Asia    | Southern Asia |               Bangladesh              |     2019    |                97.67                |              52.67              |         165.516222         |        351.24       | 130170.00  |       None       |
|   Central and Southern Asia    | Southern Asia |               Bangladesh              |     2020    |                97.67                |              54.00              |         167.420951         |        373.90       | 130170.00  |       None       |
|   Central and Southern Asia    | Southern Asia |                 Bhutan                |     2015    |                96.33                |              70.67              |          0.743274          |         2.00        |  38117.00  |       2.45       |
|   Central and Southern Asia    | Southern Asia |                 Bhutan                |     2016    |                97.00                |              71.67              |          0.749761          |         2.16        |  38144.00  |       None       |
|   Central and Southern Asia    | Southern Asia |                 Bhutan                |     2017    |                97.33                |              73.33              |          0.756121          |         2.45        |  38144.00  |       None       |
|   Central and Southern Asia    | Southern Asia |                 Bhutan                |     2018    |                97.33                |              74.33              |          0.762096          |         2.45        |  38140.00  |       3.35       |
|   Central and Southern Asia    | Southern Asia |                 Bhutan                |     2019    |                97.33                |              75.00              |          0.767459          |         2.54        |  38140.00  |       2.72       |
|   Central and Southern Asia    | Southern Asia |                 Bhutan                |     2020    |                97.33                |              76.67              |          0.772506          |         2.33        |  38140.00  |       5.03       |
|   Central and Southern Asia    | Southern Asia |                 India                 |     2015    |                89.00                |              59.33              |        1322.866505         |       2103.59       | 2973190.00 |       None       |
|   Central and Southern Asia    | Southern Asia |                 India                 |     2016    |                89.33                |              62.00              |        1338.636340         |       2294.80       | 2973190.00 |       None       |
|   Central and Southern Asia    | Southern Asia |                 India                 |     2017    |                90.00                |              64.33              |        1354.195680         |       2651.47       | 2973190.00 |       None       |
|   Central and Southern Asia    | Southern Asia |                 India                 |     2018    |                90.33                |              67.00              |        1369.003306         |       2702.93       | 2973190.00 |       7.65       |
|   Central and Southern Asia    | Southern Asia |                 India                 |     2019    |                90.67                |              69.67              |        1383.112050         |       2831.55       | 2973190.00 |       6.51       |
|   Central and Southern Asia    | Southern Asia |                 India                 |     2020    |                91.00                |              72.33              |        1396.387127         |       2667.69       | 2973190.00 |       7.86       |
|   Central and Southern Asia    | Southern Asia |       Iran (Islamic Republic of)      |     2015    |                95.67                |              86.00              |            None            |         None        |    None    |       None       |
|   Central and Southern Asia    | Southern Asia |       Iran (Islamic Republic of)      |     2016    |                96.00                |              87.00              |            None            |         None        |    None    |       None       |
|   Central and Southern Asia    | Southern Asia |       Iran (Islamic Republic of)      |     2017    |                96.33                |              87.67              |            None            |         None        |    None    |       None       |
|   Central and Southern Asia    | Southern Asia |       Iran (Islamic Republic of)      |     2018    |                96.33                |              88.00              |            None            |         None        |    None    |       None       |
|   Central and Southern Asia    | Southern Asia |       Iran (Islamic Republic of)      |     2019    |                96.33                |              88.33              |            None            |         None        |    None    |       None       |
|   Central and Southern Asia    | Southern Asia |       Iran (Islamic Republic of)      |     2020    |                96.67                |              88.33              |            None            |         None        |    None    |       None       |
|   Central and Southern Asia    | Southern Asia |                Maldives               |     2015    |                99.00                |              94.67              |          0.435582          |         4.11        |   300.00   |       None       |
|   Central and Southern Asia    | Southern Asia |                Maldives               |     2016    |                99.00                |              95.33              |          0.454252          |         4.38        |   300.00   |       5.77       |
|   Central and Southern Asia    | Southern Asia |                Maldives               |     2017    |                99.33                |              96.33              |          0.472442          |         4.75        |   300.00   |       None       |
|   Central and Southern Asia    | Southern Asia |                Maldives               |     2018    |                99.33                |              97.67              |          0.489758          |         5.30        |   300.00   |       None       |
|   Central and Southern Asia    | Southern Asia |                Maldives               |     2019    |                99.67                |              98.33              |          0.504508          |         5.61        |   300.00   |       4.56       |
|   Central and Southern Asia    | Southern Asia |                Maldives               |     2020    |                99.67                |              99.33              |          0.514438          |         3.75        |   300.00   |       None       |
|   Central and Southern Asia    | Southern Asia |                 Nepal                 |     2015    |                88.33                |              60.00              |         27.610325          |        24.36        | 143350.00  |       3.10       |
|   Central and Southern Asia    | Southern Asia |                 Nepal                 |     2016    |                88.67                |              63.00              |         27.861186          |        24.52        | 143350.00  |       None       |
|   Central and Southern Asia    | Southern Asia |                 Nepal                 |     2017    |                89.00                |              66.67              |         28.183426          |        28.97        | 143350.00  |      10.66       |
|   Central and Southern Asia    | Southern Asia |                 Nepal                 |     2018    |                89.33                |              69.67              |         28.506712          |        33.11        | 143350.00  |       None       |
|   Central and Southern Asia    | Southern Asia |                 Nepal                 |     2019    |                90.00                |              73.33              |         28.832496          |        34.19        | 143350.00  |       None       |
|   Central and Southern Asia    | Southern Asia |                 Nepal                 |     2020    |                90.00                |              76.67              |         29.348627          |        33.43        | 143350.00  |       None       |
|   Central and Southern Asia    | Southern Asia |                Pakistan               |     2015    |                90.00                |              61.67              |         210.969298         |        270.56       | 770880.00  |       3.57       |

The previous query may return a large number of rows, which could slow down our system. Modify the query to limit the number of rows returned to 10.

In [12]:
%%sql

SELECT 
    *
FROM
    Access_to_Basic_Services
LIMIT 10;

Running query in 'mysql+pymysql://root:***@localhost:3306/united_nations'

10 rows affected.

+---------------------------+--------------+--------------+-------------+-------------------------------------+---------------------------------+----------------------------+---------------------+------------+------------------+
|           Region          |  Sub_region  | Country_name | Time_period | Pct_managed_drinking_water_services | Pct_managed_sanitation_services | Est_population_in_millions | Est_gdp_in_billions | Land_area  | Pct_unemployment |
+---------------------------+--------------+--------------+-------------+-------------------------------------+---------------------------------+----------------------------+---------------------+------------+------------------+
| Central and Southern Asia | Central Asia |  Kazakhstan  |     2015    |                94.67                |              98.00              |         17.542806          |        184.39       | 2699700.00 |       4.93       |
| Central and Southern Asia | Central Asia |  Kazakhstan  |     2016    |                94.67                |              98.00              |         17.794055          |        137.28       | 2699700.00 |       4.96       |
| Central and Southern Asia | Central Asia |  Kazakhstan  |     2017    |                95.00                |              98.00              |         18.037776          |        166.81       | 2699700.00 |       4.90       |
| Central and Southern Asia | Central Asia |  Kazakhstan  |     2018    |                95.00                |              98.00              |         18.276452          |        179.34       | 2699700.00 |       4.85       |
| Central and Southern Asia | Central Asia |  Kazakhstan  |     2019    |                95.00                |              98.00              |         18.513673          |        181.67       | 2699700.00 |       4.80       |
| Central and Southern Asia | Central Asia |  Kazakhstan  |     2020    |                95.00                |              98.00              |         18.755666          |        171.08       | 2699700.00 |       4.89       |
| Central and Southern Asia | Central Asia |  Kyrgyzstan  |     2015    |                89.67                |              96.67              |            None            |         None        |    None    |       None       |
| Central and Southern Asia | Central Asia |  Kyrgyzstan  |     2016    |                90.33                |              96.67              |            None            |         None        |    None    |       None       |
| Central and Southern Asia | Central Asia |  Kyrgyzstan  |     2017    |                91.00                |              97.33              |            None            |         None        |    None    |       None       |
| Central and Southern Asia | Central Asia |  Kyrgyzstan  |     2018    |                91.33                |              97.33              |            None            |         None        |    None    |       None       |
+---------------------------+--------------+--------------+-------------+-------------------------------------+---------------------------------+----------------------------+---------------------+------------+------------------+
Truncated to displaylimit of 10.

### 2. Unique country names
Extract a list of unique country names in the database.

In [13]:
%%sql

SELECT DISTINCT
    Country_name
FROM
    Access_to_Basic_Services
LIMIT 10;

Running query in 'mysql+pymysql://root:***@localhost:3306/united_nations'

10 rows affected.

+----------------------------+
|        Country_name        |
+----------------------------+
|         Kazakhstan         |
|         Kyrgyzstan         |
|         Tajikistan         |
|        Turkmenistan        |
|         Uzbekistan         |
|        Afghanistan         |
|         Bangladesh         |
|           Bhutan           |
|           India            |
| Iran (Islamic Republic of) |
+----------------------------+
Truncated to displaylimit of 10.

Create a new table called `Country_list` and save the unique country names into this table.

In [29]:
%%sql

CREATE TABLE Country_list(Country VARCHAR(255));
INSERT INTO Country_list(Country)
SELECT DISTINCT 
    Country_name 
FROM 
    united_nations.Access_to_Basic_Services;

Running query in 'mysql+pymysql://root:***@localhost:3306/united_nations'

182 rows affected.

++
||
++
++

### 3. Selecting specific fields

Select the `country_name`, `time_period`, and `pct_managed_drinking_water_services` fields from the `Access_to_Basic_Services` table.

In [14]:
%%sql

SELECT 
    country_name, time_period, pct_managed_drinking_water_services
FROM
    Access_to_Basic_Services
LIMIT 20;

Running query in 'mysql+pymysql://root:***@localhost:3306/united_nations'

20 rows affected.

+--------------+-------------+-------------------------------------+
| country_name | time_period | pct_managed_drinking_water_services |
+--------------+-------------+-------------------------------------+
|  Kazakhstan  |     2015    |                94.67                |
|  Kazakhstan  |     2016    |                94.67                |
|  Kazakhstan  |     2017    |                95.00                |
|  Kazakhstan  |     2018    |                95.00                |
|  Kazakhstan  |     2019    |                95.00                |
|  Kazakhstan  |     2020    |                95.00                |
|  Kyrgyzstan  |     2015    |                89.67                |
|  Kyrgyzstan  |     2016    |                90.33                |
|  Kyrgyzstan  |     2017    |                91.00                |
|  Kyrgyzstan  |     2018    |                91.33                |
+--------------+-------------+-------------------------------------+
Truncated to displaylimit of 10.

Rename the `pct_managed_drinking_water_services` field to `pct_access_to_water` in your query results.

In [28]:
%%sql
    ALTER TABLE Access_to_Basic_Services
    RENAME COLUMN pct_managed_drinking_water_services to pct_access_to_water

Running query in 'mysql+pymysql://root:***@localhost:3306/united_nations'

++
||
++
++

### 4. Filtering and sorting data

Modify your query to only display data for the year `2020`.

In [20]:
%%sql
SELECT 
    *
FROM
    Access_to_Basic_Services
WHERE 
    Time_period = 2020
LIMIT 20;

Running query in 'mysql+pymysql://root:***@localhost:3306/united_nations'

20 rows affected.

+---------------------------+---------------+----------------------------+-------------+-------------------------------------+---------------------------------+----------------------------+---------------------+------------+------------------+
|           Region          |   Sub_region  |        Country_name        | Time_period | Pct_managed_drinking_water_services | Pct_managed_sanitation_services | Est_population_in_millions | Est_gdp_in_billions | Land_area  | Pct_unemployment |
+---------------------------+---------------+----------------------------+-------------+-------------------------------------+---------------------------------+----------------------------+---------------------+------------+------------------+
| Central and Southern Asia |  Central Asia |         Kazakhstan         |     2020    |                95.00                |              98.00              |         18.755666          |        171.08       | 2699700.00 |       4.89       |
| Central and Southern Asia |  Central Asia |         Kyrgyzstan         |     2020    |                92.67                |              97.67              |            None            |         None        |    None    |       None       |
| Central and Southern Asia |  Central Asia |         Tajikistan         |     2020    |                85.00                |              96.33              |          9.543207          |         8.13        | 138790.00  |       None       |
| Central and Southern Asia |  Central Asia |        Turkmenistan        |     2020    |                100.00               |              99.33              |          6.250438          |         None        | 469930.00  |       None       |
| Central and Southern Asia |  Central Asia |         Uzbekistan         |     2020    |                98.00                |              100.00             |         34.232050          |        59.89        | 440650.00  |       5.29       |
| Central and Southern Asia | Southern Asia |        Afghanistan         |     2020    |                80.33                |              54.00              |         38.972230          |        20.14        | 652230.00  |      11.71       |
| Central and Southern Asia | Southern Asia |         Bangladesh         |     2020    |                97.67                |              54.00              |         167.420951         |        373.90       | 130170.00  |       None       |
| Central and Southern Asia | Southern Asia |           Bhutan           |     2020    |                97.33                |              76.67              |          0.772506          |         2.33        |  38140.00  |       5.03       |
| Central and Southern Asia | Southern Asia |           India            |     2020    |                91.00                |              72.33              |        1396.387127         |       2667.69       | 2973190.00 |       7.86       |
| Central and Southern Asia | Southern Asia | Iran (Islamic Republic of) |     2020    |                96.67                |              88.33              |            None            |         None        |    None    |       None       |
+---------------------------+---------------+----------------------------+-------------+-------------------------------------+---------------------------------+----------------------------+---------------------+------------+------------------+
Truncated to displaylimit of 10.

The previous query may return a large number of rows, which could slow down our system. Modify the query to limit the number of rows returned to 10.

In [23]:
%%sql

SELECT 
    country_name, 
    time_period, 
    pct_managed_drinking_water_services AS pct_access_to_water
FROM 
    united_nations.Access_to_Basic_Services 
WHERE 
    Time_period = 2020
ORDER BY pct_access_to_water
LIMIT 10;

Running query in 'mysql+pymysql://root:***@localhost:3306/united_nations'

10 rows affected.

+----------------------------------+-------------+---------------------+
|           country_name           | time_period | pct_access_to_water |
+----------------------------------+-------------+---------------------+
|     Central African Republic     |     2020    |        38.33        |
| Democratic Republic of the Congo |     2020    |        47.67        |
|           South Sudan            |     2020    |        48.33        |
|              Angola              |     2020    |        52.33        |
|               Chad               |     2020    |        52.67        |
|           Burkina Faso           |     2020    |        53.33        |
|            Madagascar            |     2020    |        56.33        |
|         Papua New Guinea         |     2020    |        56.67        |
|             Somalia              |     2020    |        57.33        |
|              Niger               |     2020    |        57.33        |
+----------------------------------+-------------+---------------------+
Truncated to displaylimit of 10.

And there is the answer at the top:

In [ ]:
#Answer:

## Solutions

### 1. Exploring the database

Use the `SELECT` statement to display all the columns from the `Access_to_Basic_Services` table. This will help us get a feel for the data we're working with.

In [ ]:
%%sql

SELECT 
    * 
FROM 
    united_nations.Access_to_Basic_Services
LIMIT 30;

The previous query may return a large number of rows, which could slow down our system. Modify the query to limit the number of rows returned to 10.

In [ ]:
%%sql

SELECT 
    * 
FROM 
    united_nations.Access_to_Basic_Services
LIMIT 10;

### 2. Unique country names
Extract a list of unique country names in the database.

In [ ]:
%%sql

SELECT DISTINCT 
    Country_name 
FROM 
    united_nations.Access_to_Basic_Services
    LIMIT 20;

Create a new table called `Country_list` and save the unique country names into this table.

In [ ]:
%%sql

CREATE TABLE Country_list(Country VARCHAR(255));
INSERT INTO Country_list(Country)
SELECT DISTINCT 
    Country_name 
FROM 
    united_nations.Access_to_Basic_Services;

### 3. Selecting specific fields

Select the `country_name`, `time_period`, and `pct_managed_drinking_water_services` fields from the `Access_to_Basic_Services` table.

In [ ]:
%%sql

SELECT 
    country_name, 
    time_period, 
    pct_managed_drinking_water_services 
FROM 
    united_nations.Access_to_Basic_Services
LIMIT 20;

Rename the `pct_managed_drinking_water_services` field to `pct_access_to_water` in your query results.

In [ ]:
%%sql

SELECT 
    country_name, 
    time_period, 
    pct_managed_drinking_water_services AS pct_access_to_water
FROM 
    united_nations.Access_to_Basic_Services
LIMIT 20

### 4. Filtering and sorting data

Modify your query to only display data for the year 2020.

In [ ]:
%%sql

SELECT 
    country_name, 
    time_period, 
    pct_managed_drinking_water_services AS pct_access_to_water
FROM 
    united_nations.Access_to_Basic_Services 
WHERE 
    Time_period = 2020
LIMIT 100;

The previous query may return a large number of rows, which could slow down our system. Modify the query to limit the number of rows returned to 10.

In [ ]:
%%sql

SELECT 
    country_name, 
    time_period, 
    pct_managed_drinking_water_services AS pct_access_to_water
FROM 
    united_nations.Access_to_Basic_Services 
WHERE 
    Time_period = 2020
ORDER BY pct_access_to_water
LIMIT 10;

## Summary
Congratulations! You have used SQL commands to filter and sort data to answer a specific question. Please review your results and think about what other questions could be answered with this data.

#  

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/refs/heads/master/ALX_banners/ALX_Navy.png"  style="width:100px"  ;/>
</div>